name: CraftedGateway
main: net.sanctuary.servers.craftedgateway.CraftedGatewayPlugin
version: ${version}
api-version: "1.20"
permissions:
  craftedgateway.votd.reload:
    description: Reload VOTD configuration.
    default: op
